// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRR6kHBizB6b073xEc8c32QWZSbJmuZz4',
    appId: '1:23981252288:web:82576c29e4435f0d961725',
    messagingSenderId: '23981252288',
    projectId: 'makeathon7-app',
    authDomain: 'makeathon7-app.firebaseapp.com',
    storageBucket: 'makeathon7-app.firebasestorage.app',
    measurementId: 'G-CJY2EXESVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcrnyQLLZ0q50mkvf1-mZqr3pisJoq36w',
    appId: '1:23981252288:android:5c9b5df540d15ec6961725',
    messagingSenderId: '23981252288',
    projectId: 'makeathon7-app',
    storageBucket: 'makeathon7-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCymroe0z0D1LRSsECnsLh4G3AM3_26GJE',
    appId: '1:23981252288:ios:8aff561268034533961725',
    messagingSenderId: '23981252288',
    projectId: 'makeathon7-app',
    storageBucket: 'makeathon7-app.firebasestorage.app',
    iosBundleId: 'com.example.makeathon7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCymroe0z0D1LRSsECnsLh4G3AM3_26GJE',
    appId: '1:23981252288:ios:8aff561268034533961725',
    messagingSenderId: '23981252288',
    projectId: 'makeathon7-app',
    storageBucket: 'makeathon7-app.firebasestorage.app',
    iosBundleId: 'com.example.makeathon7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRR6kHBizB6b073xEc8c32QWZSbJmuZz4',
    appId: '1:23981252288:web:5eac14407754234c961725',
    messagingSenderId: '23981252288',
    projectId: 'makeathon7-app',
    authDomain: 'makeathon7-app.firebaseapp.com',
    storageBucket: 'makeathon7-app.firebasestorage.app',
    measurementId: 'G-SE2V7CLBQ2',
  );
}
